services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: antisludge
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./apps/api/database:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d antisludge"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - anti-sludge-net

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    image: anti-sludge-api:latest
    restart: unless-stopped
    environment:
      - DB_USER=admin
      - DB_PASS=secret
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=antisludge
      - DB_SSLMODE=disable
      - DEBUG=True
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - anti-sludge-net

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=/api/v1
    image: anti-sludge-web:latest
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - anti-sludge-net

  nginx:
    build:
      context: ./infra/nginx
      dockerfile: Dockerfile
    image: anti-sludge-nginx:latest
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./infra/certbot/conf:/etc/letsencrypt:ro
      - ./infra/certbot/www:/var/www/certbot:ro
    depends_on:
      - web
      - api
    networks:
      - anti-sludge-net

  certbot:
    image: infinityofspace/certbot_dns_duckdns:latest
    volumes:
      - ./infra/certbot/conf:/etc/letsencrypt
    environment:
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
    # O comando abaixo será usado para renovação automática após a primeira emissão
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --dns-duckdns --dns-duckdns-token ${DUCKDNS_TOKEN}; sleep 12h & wait $${!}; done;'"
    networks:
      - anti-sludge-net

networks:
  anti-sludge-net:
    driver: bridge

volumes:
  postgres_data:
