"""Baseline

Revision ID: a1a3a8ab2ab9
Revises:
Create Date: 2026-04-13 01:54:09.563783

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a1a3a8ab2ab9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
	"""Upgrade schema."""
	# Habilitar extensão para UUID
	op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')

	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"categoria",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("nome", sa.String(length=100), nullable=False),
		sa.Column("conceito", sa.Text(), nullable=True),
		sa.Column("exemplos", sa.Text(), nullable=True),
		sa.Column("descricao", sa.Text(), nullable=True),
		sa.Column("quantidade_tipos", sa.Integer(), server_default="0", nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=False,
		),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("nome"),
	)
	op.create_table(
		"glossario",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("termo", sa.String(length=150), nullable=False),
		sa.Column("grupo", sa.String(length=100), nullable=True),
		sa.Column("definicao", sa.Text(), nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=False,
		),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("termo"),
	)
	op.create_table(
		"grupo_analise",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("nome", sa.String(length=100), nullable=False),
		sa.Column("descricao", sa.Text(), nullable=False),
		sa.Column("criterios_considerados", sa.Text(), nullable=True),
		sa.Column(
			"created_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=False,
		),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("nome"),
	)
	op.create_table(
		"observador",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("nome", sa.String(length=150), nullable=False),
		sa.Column("email", sa.String(length=255), nullable=True),
		sa.Column("estado", sa.String(length=50), nullable=True),
		sa.Column("escolaridade", sa.String(length=100), nullable=True),
		sa.Column(
			"created_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=False,
		),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_table(
		"processo",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column(
			"uuid",
			sa.UUID(),
			server_default=sa.text("uuid_generate_v4()"),
			nullable=False,
		),
		sa.Column("nome", sa.String(length=255), nullable=False),
		sa.Column("descricao", sa.Text(), nullable=True),
		sa.Column("objetivo", sa.Text(), nullable=True),
		sa.Column(
			"esfera_governo",
			sa.Enum("Federal", "Estadual", "Municipal", name="esfera_governo_enum"),
			nullable=True,
		),
		sa.Column(
			"abrangencia",
			sa.Enum("Público Geral", "Público Específico", name="abrangencia_enum"),
			nullable=True,
		),
		sa.Column("publico_alvo", sa.Text(), nullable=True),
		sa.Column("usuarios_estimados_ano", sa.Integer(), nullable=True),
		sa.Column("perfil_foco_mapeamento", sa.Text(), nullable=True),
		sa.Column("jornada_planejada_descricao", sa.Text(), nullable=True),
		sa.Column("necessidade_usuario", sa.Text(), nullable=True),
		sa.Column("tempo_medio_estimado", sa.String(length=50), nullable=True),
		sa.Column("indicadores_desempenho", sa.Text(), nullable=True),
		sa.Column("hipoteses_dificuldades", sa.Text(), nullable=True),
		sa.Column("registros_reclamacao", sa.Text(), nullable=True),
		sa.Column("registros_satisfacao", sa.Text(), nullable=True),
		sa.Column(
			"status",
			sa.String(length=50),
			server_default=sa.text("'Em Andamento'"),
			nullable=False,
		),
		sa.Column(
			"created_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=False,
		),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("uuid"),
	)
	op.create_index("idx_processo_nome", "processo", ["nome"], unique=False)
	op.create_index("idx_processo_status", "processo", ["status"], unique=False)
	op.create_table(
		"criterio_template",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("nome", sa.String(length=100), nullable=False),
		sa.Column("conceito", sa.Text(), nullable=False),
		sa.Column("grupo_analise_id", sa.Integer(), nullable=True),
		sa.Column(
			"created_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(
			["grupo_analise_id"], ["grupo_analise.id"], ondelete="SET NULL"
		),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("nome"),
	)
	op.create_table(
		"jornada_observada",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("processo_id", sa.Integer(), nullable=False),
		sa.Column("observador_id", sa.Integer(), nullable=True),
		sa.Column("protocolo", sa.String(length=50), nullable=False),
		sa.Column("nome_jornada", sa.String(length=100), nullable=True),
		sa.Column("data_observacao", sa.Date(), nullable=False),
		sa.Column("observacoes_gerais", sa.Text(), nullable=True),
		sa.Column(
			"created_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(
			["observador_id"], ["observador.id"], ondelete="SET NULL"
		),
		sa.ForeignKeyConstraint(["processo_id"], ["processo.id"], ondelete="CASCADE"),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("protocolo"),
	)
	op.create_index(
		"idx_jornada_data", "jornada_observada", ["data_observacao"], unique=False
	)
	op.create_index(
		"idx_jornada_processo", "jornada_observada", ["processo_id"], unique=False
	)
	op.create_table(
		"tipo_comportamento",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("categoria_id", sa.Integer(), nullable=False),
		sa.Column("nome", sa.String(length=100), nullable=False),
		sa.Column("codigo_referencia", sa.String(length=50), nullable=False),
		sa.Column("conceito", sa.Text(), nullable=True),
		sa.Column("exemplos", sa.Text(), nullable=True),
		sa.Column("descricao", sa.Text(), nullable=True),
		sa.Column("num_criterios", sa.Integer(), server_default="0", nullable=False),
		sa.Column(
			"ordem_na_categoria", sa.Integer(), server_default="1", nullable=False
		),
		sa.Column(
			"created_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(
			["categoria_id"], ["categoria.id"], ondelete="RESTRICT"
		),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("codigo_referencia"),
		sa.UniqueConstraint("nome"),
	)
	op.create_table(
		"escala_avaliacao",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("criterio_template_id", sa.Integer(), nullable=True),
		sa.Column("tipo_comportamento_id", sa.Integer(), nullable=True),
		sa.Column("pergunta", sa.Text(), nullable=False),
		sa.Column("texto_nota_1", sa.Text(), nullable=False),
		sa.Column("texto_nota_2", sa.Text(), nullable=True),
		sa.Column("texto_nota_3", sa.Text(), nullable=True),
		sa.Column("texto_nota_4", sa.Text(), nullable=True),
		sa.Column("texto_nota_5", sa.Text(), nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(
			["criterio_template_id"], ["criterio_template.id"], ondelete="SET NULL"
		),
		sa.ForeignKeyConstraint(
			["tipo_comportamento_id"], ["tipo_comportamento.id"], ondelete="SET NULL"
		),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_table(
		"etapa",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("processo_id", sa.Integer(), nullable=False),
		sa.Column("categoria_id", sa.Integer(), nullable=False),
		sa.Column("tipo_comportamento_id", sa.Integer(), nullable=False),
		sa.Column("numero", sa.String(length=10), nullable=True),
		sa.Column("comportamento", sa.String(length=500), nullable=False),
		sa.Column(
			"e_obrigatorio",
			sa.Boolean(),
			server_default=sa.text("false"),
			nullable=False,
		),
		sa.Column("repeticoes", sa.String(length=50), nullable=True),
		sa.Column("tempo_planejado", postgresql.INTERVAL(), nullable=True),
		sa.Column("tempo_padrao", postgresql.INTERVAL(), nullable=True),
		sa.Column("ordem", sa.Integer(), nullable=False),
		sa.Column("duracao_media_observada", postgresql.INTERVAL(), nullable=True),
		sa.Column(
			"created_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(
			["categoria_id"], ["categoria.id"], ondelete="RESTRICT"
		),
		sa.ForeignKeyConstraint(["processo_id"], ["processo.id"], ondelete="CASCADE"),
		sa.ForeignKeyConstraint(
			["tipo_comportamento_id"], ["tipo_comportamento.id"], ondelete="RESTRICT"
		),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_index("idx_etapa_ordem", "etapa", ["processo_id", "ordem"], unique=False)
	op.create_index("idx_etapa_processo", "etapa", ["processo_id"], unique=False)
	op.create_table(
		"tipo_criterio",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("tipo_comportamento_id", sa.Integer(), nullable=False),
		sa.Column("criterio_template_id", sa.Integer(), nullable=False),
		sa.Column("ordem", sa.Integer(), server_default="1", nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(
			["criterio_template_id"], ["criterio_template.id"], ondelete="CASCADE"
		),
		sa.ForeignKeyConstraint(
			["tipo_comportamento_id"], ["tipo_comportamento.id"], ondelete="CASCADE"
		),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint(
			"tipo_comportamento_id", "criterio_template_id", name="uq_tipo_criterio"
		),
	)
	op.create_table(
		"criterio_barreira",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("etapa_id", sa.Integer(), nullable=False),
		sa.Column("criterio_template_id", sa.Integer(), nullable=True),
		sa.Column("nome", sa.String(length=100), nullable=False),
		sa.Column("pergunta", sa.Text(), nullable=False),
		sa.Column("texto_nota_1", sa.Text(), nullable=True),
		sa.Column("texto_nota_5", sa.Text(), nullable=True),
		sa.Column("ordem", sa.Integer(), server_default="1", nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(
			["criterio_template_id"], ["criterio_template.id"], ondelete="SET NULL"
		),
		sa.ForeignKeyConstraint(["etapa_id"], ["etapa.id"], ondelete="CASCADE"),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_index(
		"idx_criterio_barreira_etapa", "criterio_barreira", ["etapa_id"], unique=False
	)
	op.create_table(
		"criterio_impacto",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("etapa_id", sa.Integer(), nullable=False),
		sa.Column(
			"nome",
			sa.Enum(
				"Carga Cognitiva",
				"Emoção",
				"Consequência",
				name="criterio_impacto_enum",
			),
			nullable=False,
		),
		sa.Column("pergunta", sa.Text(), nullable=False),
		sa.Column("texto_nota_1", sa.Text(), nullable=True),
		sa.Column("texto_nota_5", sa.Text(), nullable=True),
		sa.Column("ordem", sa.Integer(), server_default="1", nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(["etapa_id"], ["etapa.id"], ondelete="CASCADE"),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_index(
		"idx_criterio_impacto_etapa", "criterio_impacto", ["etapa_id"], unique=False
	)
	op.create_table(
		"resultado_analise",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("processo_id", sa.Integer(), nullable=False),
		sa.Column("etapa_id", sa.Integer(), nullable=True),
		sa.Column("media_barreiras", sa.Numeric(precision=3, scale=2), nullable=True),
		sa.Column("media_impactos", sa.Numeric(precision=3, scale=2), nullable=True),
		sa.Column("indice_sludge", sa.Numeric(precision=5, scale=2), nullable=True),
		sa.Column("prioridade", sa.Integer(), nullable=True),
		sa.Column("e_sludge", sa.Boolean(), server_default="false", nullable=False),
		sa.Column("recomendacoes", sa.Text(), nullable=True),
		sa.Column(
			"created_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(["etapa_id"], ["etapa.id"], ondelete="SET NULL"),
		sa.ForeignKeyConstraint(["processo_id"], ["processo.id"], ondelete="CASCADE"),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_index(
		"idx_resultado_processo", "resultado_analise", ["processo_id"], unique=False
	)
	op.create_table(
		"tempo_etapa",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("jornada_observada_id", sa.Integer(), nullable=False),
		sa.Column("etapa_id", sa.Integer(), nullable=False),
		sa.Column("tempo_realizado", postgresql.INTERVAL(), nullable=False),
		sa.Column("observacao", sa.Text(), nullable=True),
		sa.Column(
			"created_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(["etapa_id"], ["etapa.id"], ondelete="CASCADE"),
		sa.ForeignKeyConstraint(
			["jornada_observada_id"], ["jornada_observada.id"], ondelete="CASCADE"
		),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("jornada_observada_id", "etapa_id", name="uq_tempo_etapa"),
	)
	op.create_index("idx_tempo_etapa_etapa", "tempo_etapa", ["etapa_id"], unique=False)
	op.create_table(
		"avaliacao_barreira",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("criterio_barreira_id", sa.Integer(), nullable=False),
		sa.Column("jornada_observada_id", sa.Integer(), nullable=True),
		sa.Column("nota", sa.SmallInteger(), nullable=True),
		sa.Column(
			"tipo_evidencia",
			sa.Enum(
				"Fala",
				"Comportamento no sistema",
				"Fala e Comportamento no sistema",
				name="tipo_evidencia_enum",
			),
			nullable=True,
		),
		sa.Column("observacao", sa.Text(), nullable=True),
		sa.Column(
			"data_avaliacao",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=False,
		),
		sa.CheckConstraint(
			"nota IS NULL OR (nota >= 1 AND nota <= 5)", name="ck_av_barreira_nota_1_5"
		),
		sa.ForeignKeyConstraint(
			["criterio_barreira_id"], ["criterio_barreira.id"], ondelete="CASCADE"
		),
		sa.ForeignKeyConstraint(
			["jornada_observada_id"], ["jornada_observada.id"], ondelete="SET NULL"
		),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_index(
		"idx_avaliacao_barreira_criterio",
		"avaliacao_barreira",
		["criterio_barreira_id"],
		unique=False,
	)
	op.create_index(
		"idx_avaliacao_barreira_jornada",
		"avaliacao_barreira",
		["jornada_observada_id"],
		unique=False,
	)
	op.create_table(
		"avaliacao_impacto",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("criterio_impacto_id", sa.Integer(), nullable=False),
		sa.Column("jornada_observada_id", sa.Integer(), nullable=True),
		sa.Column("nota", sa.SmallInteger(), nullable=True),
		sa.Column(
			"tipo_evidencia",
			sa.Enum(
				"Fala",
				"Comportamento no sistema",
				"Fala e Comportamento no sistema",
				name="tipo_evidencia_enum",
			),
			nullable=True,
		),
		sa.Column("observacao", sa.Text(), nullable=True),
		sa.Column(
			"data_avaliacao",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=False,
		),
		sa.CheckConstraint(
			"nota IS NULL OR (nota >= 1 AND nota <= 5)", name="ck_av_impacto_nota_1_5"
		),
		sa.ForeignKeyConstraint(
			["criterio_impacto_id"], ["criterio_impacto.id"], ondelete="CASCADE"
		),
		sa.ForeignKeyConstraint(
			["jornada_observada_id"], ["jornada_observada.id"], ondelete="SET NULL"
		),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_index(
		"idx_avaliacao_impacto_criterio",
		"avaliacao_impacto",
		["criterio_impacto_id"],
		unique=False,
	)
	op.create_index(
		"idx_avaliacao_impacto_jornada",
		"avaliacao_impacto",
		["jornada_observada_id"],
		unique=False,
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_index("idx_avaliacao_impacto_jornada", table_name="avaliacao_impacto")
	op.drop_index("idx_avaliacao_impacto_criterio", table_name="avaliacao_impacto")
	op.drop_table("avaliacao_impacto")
	op.drop_index("idx_avaliacao_barreira_jornada", table_name="avaliacao_barreira")
	op.drop_index("idx_avaliacao_barreira_criterio", table_name="avaliacao_barreira")
	op.drop_table("avaliacao_barreira")
	op.drop_index("idx_tempo_etapa_etapa", table_name="tempo_etapa")
	op.drop_table("tempo_etapa")
	op.drop_index("idx_resultado_processo", table_name="resultado_analise")
	op.drop_table("resultado_analise")
	op.drop_index("idx_criterio_impacto_etapa", table_name="criterio_impacto")
	op.drop_table("criterio_impacto")
	op.drop_index("idx_criterio_barreira_etapa", table_name="criterio_barreira")
	op.drop_table("criterio_barreira")
	op.drop_table("tipo_criterio")
	op.drop_index("idx_etapa_processo", table_name="etapa")
	op.drop_index("idx_etapa_ordem", table_name="etapa")
	op.drop_table("etapa")
	op.drop_table("escala_avaliacao")
	op.drop_table("tipo_comportamento")
	op.drop_index("idx_jornada_processo", table_name="jornada_observada")
	op.drop_index("idx_jornada_data", table_name="jornada_observada")
	op.drop_table("jornada_observada")
	op.drop_table("criterio_template")
	op.drop_index("idx_processo_status", table_name="processo")
	op.drop_index("idx_processo_nome", table_name="processo")
	op.drop_table("processo")
	op.drop_table("observador")
	op.drop_table("grupo_analise")
	op.drop_table("glossario")
	op.drop_table("categoria")
	# ### end Alembic commands ###
