"""add_padrao_url_to_processo

Revision ID: c0f665f3d482
Revises: eb75a3dd4a42
Create Date: 2026-04-27 02:19:12.876595

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c0f665f3d482"
down_revision: str | None = "eb75a3dd4a42"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column(
		"processo", sa.Column("padrao_url", sa.String(length=500), nullable=True)
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column("processo", "padrao_url")
	# ### end Alembic commands ###
