"""create_rbac_emails_table

Revision ID: e30b485d1b00
Revises: e2730d4d224b
Create Date: 2026-04-25 16:48:23.450034

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e30b485d1b00"
down_revision: str | None = "e2730d4d224b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"rbac_emails",
		sa.Column("email", sa.String(length=255), nullable=False),
		sa.Column("role", sa.String(length=50), nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(),
			server_default=sa.text("CURRENT_TIMESTAMP"),
			nullable=False,
		),
		sa.PrimaryKeyConstraint("email"),
	)
	op.alter_column(
		"avaliacao_barreira",
		"data_avaliacao",
		existing_type=postgresql.TIMESTAMP(),
		nullable=False,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.alter_column(
		"avaliacao_impacto",
		"data_avaliacao",
		existing_type=postgresql.TIMESTAMP(),
		nullable=False,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.alter_column(
		"categoria",
		"conceito",
		existing_type=sa.TEXT(),
		comment=None,
		existing_comment="Definição conceitual da categoria",
		existing_nullable=True,
	)
	op.alter_column(
		"categoria",
		"exemplos",
		existing_type=sa.TEXT(),
		comment=None,
		existing_comment="Exemplos práticos de comportamentos",
		existing_nullable=True,
	)
	op.alter_column(
		"categoria",
		"quantidade_tipos",
		existing_type=sa.INTEGER(),
		nullable=False,
		existing_server_default=sa.text("0"),
	)
	op.alter_column(
		"categoria",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=False,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.drop_table_comment(
		"categoria",
		existing_comment="Categorias de comportamentos do usuário na jornada digital",
		schema=None,
	)
	op.alter_column(
		"criterio_barreira",
		"ordem",
		existing_type=sa.INTEGER(),
		nullable=False,
		existing_server_default=sa.text("1"),
	)
	op.alter_column(
		"criterio_barreira",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=False,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.alter_column(
		"criterio_impacto",
		"ordem",
		existing_type=sa.INTEGER(),
		nullable=False,
		existing_server_default=sa.text("1"),
	)
	op.alter_column(
		"criterio_impacto",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=False,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.alter_column(
		"criterio_template",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=False,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.create_foreign_key(
		None,
		"criterio_template",
		"grupo_analise",
		["grupo_analise_id"],
		["id"],
		ondelete="SET NULL",
	)
	op.drop_table_comment(
		"criterio_template",
		existing_comment="Template dos 14 critérios de avaliação de barreiras",
		schema=None,
	)
	op.alter_column(
		"escala_avaliacao",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=False,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.drop_table_comment(
		"escala_avaliacao",
		existing_comment="Escalas detalhadas de 1 a 5 para cada combinação critério+tipo",
		schema=None,
	)
	op.alter_column(
		"etapa",
		"comportamento",
		existing_type=sa.VARCHAR(length=500),
		comment=None,
		existing_comment="Descrição da ação do usuário nesta etapa",
		existing_nullable=False,
	)
	op.alter_column(
		"etapa",
		"e_obrigatorio",
		existing_type=sa.BOOLEAN(),
		nullable=False,
		existing_server_default=sa.text("false"),
	)
	op.alter_column(
		"etapa",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=False,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.drop_table_comment(
		"etapa",
		existing_comment="Etapas/passos da jornada do usuário no processo",
		schema=None,
	)
	op.alter_column(
		"glossario",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=False,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.drop_table_comment(
		"glossario",
		existing_comment="Glossário completo de termos da metodologia F5",
		schema=None,
	)
	op.alter_column(
		"grupo_analise",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=False,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.drop_table_comment(
		"grupo_analise",
		existing_comment="Grupos/Lentes de análise que agrupam critérios",
		schema=None,
	)
	op.alter_column(
		"jornada_observada",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=False,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.alter_column(
		"observador",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=False,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.alter_column(
		"processo",
		"uuid",
		existing_type=sa.UUID(),
		nullable=False,
		existing_server_default=sa.text("uuid_generate_v4()"),
	)
	op.alter_column(
		"processo",
		"status",
		existing_type=sa.VARCHAR(length=50),
		nullable=False,
		existing_server_default=sa.text("'Em Andamento'::character varying"),
	)
	op.alter_column(
		"processo",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=False,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.alter_column(
		"processo",
		"updated_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=False,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.alter_column(
		"resultado_analise",
		"e_sludge",
		existing_type=sa.BOOLEAN(),
		nullable=False,
		existing_server_default=sa.text("false"),
	)
	op.alter_column(
		"resultado_analise",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=False,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.alter_column(
		"tempo_etapa",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=False,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.drop_index("idx_tempo_etapa", table_name="tempo_etapa")
	op.drop_constraint(
		"tempo_etapa_jornada_observada_id_etapa_id_key", "tempo_etapa", type_="unique"
	)
	op.create_index("idx_tempo_etapa_etapa", "tempo_etapa", ["etapa_id"], unique=False)
	op.create_unique_constraint(
		"uq_tempo_etapa", "tempo_etapa", ["jornada_observada_id", "etapa_id"]
	)
	op.alter_column(
		"tipo_comportamento",
		"codigo_referencia",
		existing_type=sa.VARCHAR(length=50),
		comment=None,
		existing_comment="Código abreviado ex: Bus - Procurar site ou aplicativo",
		existing_nullable=False,
	)
	op.alter_column(
		"tipo_comportamento",
		"num_criterios",
		existing_type=sa.INTEGER(),
		nullable=False,
		existing_server_default=sa.text("0"),
	)
	op.alter_column(
		"tipo_comportamento",
		"ordem_na_categoria",
		existing_type=sa.INTEGER(),
		nullable=False,
		existing_server_default=sa.text("1"),
	)
	op.alter_column(
		"tipo_comportamento",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=False,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.drop_table_comment(
		"tipo_comportamento",
		existing_comment="Tipos específicos de comportamento dentro de cada categoria",
		schema=None,
	)
	op.alter_column(
		"tipo_criterio",
		"ordem",
		existing_type=sa.INTEGER(),
		nullable=False,
		existing_server_default=sa.text("1"),
	)
	op.alter_column(
		"tipo_criterio",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=False,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.drop_constraint(
		"tipo_criterio_tipo_comportamento_id_criterio_template_id_key",
		"tipo_criterio",
		type_="unique",
	)
	op.create_unique_constraint(
		"uq_tipo_criterio",
		"tipo_criterio",
		["tipo_comportamento_id", "criterio_template_id"],
	)
	op.drop_table_comment(
		"tipo_criterio",
		existing_comment="Mapeamento de quais critérios se aplicam a cada tipo de comportamento",
		schema=None,
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table_comment(
		"tipo_criterio",
		"Mapeamento de quais critérios se aplicam a cada tipo de comportamento",
		existing_comment=None,
		schema=None,
	)
	op.drop_constraint("uq_tipo_criterio", "tipo_criterio", type_="unique")
	op.create_unique_constraint(
		"tipo_criterio_tipo_comportamento_id_criterio_template_id_key",
		"tipo_criterio",
		["tipo_comportamento_id", "criterio_template_id"],
		postgresql_nulls_not_distinct=False,
	)
	op.alter_column(
		"tipo_criterio",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=True,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.alter_column(
		"tipo_criterio",
		"ordem",
		existing_type=sa.INTEGER(),
		nullable=True,
		existing_server_default=sa.text("1"),
	)
	op.create_table_comment(
		"tipo_comportamento",
		"Tipos específicos de comportamento dentro de cada categoria",
		existing_comment=None,
		schema=None,
	)
	op.alter_column(
		"tipo_comportamento",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=True,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.alter_column(
		"tipo_comportamento",
		"ordem_na_categoria",
		existing_type=sa.INTEGER(),
		nullable=True,
		existing_server_default=sa.text("1"),
	)
	op.alter_column(
		"tipo_comportamento",
		"num_criterios",
		existing_type=sa.INTEGER(),
		nullable=True,
		existing_server_default=sa.text("0"),
	)
	op.alter_column(
		"tipo_comportamento",
		"codigo_referencia",
		existing_type=sa.VARCHAR(length=50),
		comment="Código abreviado ex: Bus - Procurar site ou aplicativo",
		existing_nullable=False,
	)
	op.drop_constraint("uq_tempo_etapa", "tempo_etapa", type_="unique")
	op.drop_index("idx_tempo_etapa_etapa", table_name="tempo_etapa")
	op.create_unique_constraint(
		"tempo_etapa_jornada_observada_id_etapa_id_key",
		"tempo_etapa",
		["jornada_observada_id", "etapa_id"],
		postgresql_nulls_not_distinct=False,
	)
	op.create_index("idx_tempo_etapa", "tempo_etapa", ["etapa_id"], unique=False)
	op.alter_column(
		"tempo_etapa",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=True,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.alter_column(
		"resultado_analise",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=True,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.alter_column(
		"resultado_analise",
		"e_sludge",
		existing_type=sa.BOOLEAN(),
		nullable=True,
		existing_server_default=sa.text("false"),
	)
	op.alter_column(
		"processo",
		"updated_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=True,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.alter_column(
		"processo",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=True,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.alter_column(
		"processo",
		"status",
		existing_type=sa.VARCHAR(length=50),
		nullable=True,
		existing_server_default=sa.text("'Em Andamento'::character varying"),
	)
	op.alter_column(
		"processo",
		"uuid",
		existing_type=sa.UUID(),
		nullable=True,
		existing_server_default=sa.text("uuid_generate_v4()"),
	)
	op.alter_column(
		"observador",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=True,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.alter_column(
		"jornada_observada",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=True,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.create_table_comment(
		"grupo_analise",
		"Grupos/Lentes de análise que agrupam critérios",
		existing_comment=None,
		schema=None,
	)
	op.alter_column(
		"grupo_analise",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=True,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.create_table_comment(
		"glossario",
		"Glossário completo de termos da metodologia F5",
		existing_comment=None,
		schema=None,
	)
	op.alter_column(
		"glossario",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=True,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.create_table_comment(
		"etapa",
		"Etapas/passos da jornada do usuário no processo",
		existing_comment=None,
		schema=None,
	)
	op.alter_column(
		"etapa",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=True,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.alter_column(
		"etapa",
		"e_obrigatorio",
		existing_type=sa.BOOLEAN(),
		nullable=True,
		existing_server_default=sa.text("false"),
	)
	op.alter_column(
		"etapa",
		"comportamento",
		existing_type=sa.VARCHAR(length=500),
		comment="Descrição da ação do usuário nesta etapa",
		existing_nullable=False,
	)
	op.create_table_comment(
		"escala_avaliacao",
		"Escalas detalhadas de 1 a 5 para cada combinação critério+tipo",
		existing_comment=None,
		schema=None,
	)
	op.alter_column(
		"escala_avaliacao",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=True,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.create_table_comment(
		"criterio_template",
		"Template dos 14 critérios de avaliação de barreiras",
		existing_comment=None,
		schema=None,
	)
	op.drop_constraint(None, "criterio_template", type_="foreignkey")
	op.alter_column(
		"criterio_template",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=True,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.alter_column(
		"criterio_impacto",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=True,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.alter_column(
		"criterio_impacto",
		"ordem",
		existing_type=sa.INTEGER(),
		nullable=True,
		existing_server_default=sa.text("1"),
	)
	op.alter_column(
		"criterio_barreira",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=True,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.alter_column(
		"criterio_barreira",
		"ordem",
		existing_type=sa.INTEGER(),
		nullable=True,
		existing_server_default=sa.text("1"),
	)
	op.create_table_comment(
		"categoria",
		"Categorias de comportamentos do usuário na jornada digital",
		existing_comment=None,
		schema=None,
	)
	op.alter_column(
		"categoria",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		nullable=True,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.alter_column(
		"categoria",
		"quantidade_tipos",
		existing_type=sa.INTEGER(),
		nullable=True,
		existing_server_default=sa.text("0"),
	)
	op.alter_column(
		"categoria",
		"exemplos",
		existing_type=sa.TEXT(),
		comment="Exemplos práticos de comportamentos",
		existing_nullable=True,
	)
	op.alter_column(
		"categoria",
		"conceito",
		existing_type=sa.TEXT(),
		comment="Definição conceitual da categoria",
		existing_nullable=True,
	)
	op.alter_column(
		"avaliacao_impacto",
		"data_avaliacao",
		existing_type=postgresql.TIMESTAMP(),
		nullable=True,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.alter_column(
		"avaliacao_barreira",
		"data_avaliacao",
		existing_type=postgresql.TIMESTAMP(),
		nullable=True,
		existing_server_default=sa.text("CURRENT_TIMESTAMP"),
	)
	op.drop_table("rbac_emails")
	# ### end Alembic commands ###
