"""update_extension_session_limits

Revision ID: eb75a3dd4a42
Revises: e30b485d1b00
Create Date: 2026-04-27 01:18:42.059281

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eb75a3dd4a42"
down_revision: str | None = "e30b485d1b00"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.alter_column(
		"interacao_extensao",
		"elemento_tag",
		existing_type=sa.VARCHAR(length=50),
		type_=sa.String(length=100),
		existing_nullable=True,
	)
	op.alter_column(
		"interacao_extensao",
		"elemento_id",
		existing_type=sa.VARCHAR(length=200),
		type_=sa.String(length=255),
		existing_nullable=True,
	)
	op.alter_column(
		"interacao_extensao",
		"elemento_classe",
		existing_type=sa.VARCHAR(length=500),
		type_=sa.String(length=1000),
		existing_nullable=True,
	)
	op.alter_column(
		"interacao_extensao",
		"elemento_texto",
		existing_type=sa.VARCHAR(length=200),
		type_=sa.String(length=1000),
		existing_nullable=True,
	)
	op.alter_column(
		"pagina_extensao",
		"titulo",
		existing_type=sa.VARCHAR(length=500),
		type_=sa.String(length=1000),
		existing_nullable=True,
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.alter_column(
		"pagina_extensao",
		"titulo",
		existing_type=sa.String(length=1000),
		type_=sa.VARCHAR(length=500),
		existing_nullable=True,
	)
	op.alter_column(
		"interacao_extensao",
		"elemento_texto",
		existing_type=sa.String(length=1000),
		type_=sa.VARCHAR(length=200),
		existing_nullable=True,
	)
	op.alter_column(
		"interacao_extensao",
		"elemento_classe",
		existing_type=sa.String(length=1000),
		type_=sa.VARCHAR(length=500),
		existing_nullable=True,
	)
	op.alter_column(
		"interacao_extensao",
		"elemento_id",
		existing_type=sa.String(length=255),
		type_=sa.VARCHAR(length=200),
		existing_nullable=True,
	)
	op.alter_column(
		"interacao_extensao",
		"elemento_tag",
		existing_type=sa.String(length=100),
		type_=sa.VARCHAR(length=50),
		existing_nullable=True,
	)
	# ### end Alembic commands ###
